"""many to many conversations materialsOpen

Revision ID: c12f0e25cdd6
Revises: 45037920c816
Create Date: 2026-05-23 09:08:06.075176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12f0e25cdd6'
down_revision: Union[str, None] = '45037920c816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_materials',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'material_id')
    )
    op.drop_constraint('conversations_material_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'material_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('conversations_material_id_fkey', 'conversations', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_table('conversation_materials')
    # ### end Alembic commands ###
